"""initial migration

Revision ID: 4d216cad0e21
Revises: 
Create Date: 2024-01-10 00:04:12.225892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d216cad0e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_map_timestamp', table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(length=256), nullable=False),
    sa.Column('short', sa.VARCHAR(length=128), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_map_timestamp', 'url_map', ['timestamp'], unique=False)
    # ### end Alembic commands ###
